config/routes.rb
Roadmap::Application.routes.draw do
  root to: 'projects#index'

  resources :projects do 
    get "billing", controller: 'projects/reports', action: :billing
    get "billing_detail", controller: 'projects/reports', action: :billing_detail
    put 'run_refresh', controller: 'projects/refresh', action: :run_refresh
    get 'refresh', controller: 'projects/refresh', action: :refresh
    post 'schedule', controller: 'features', action: :schedule

    resources :features do
      get 'tagged/:value',
        :constraints => { :value =>  /[^\/]+/ },
        on: :collection, 
        action: :tagged,
        as: 'tagged'
    end

    resources :bundles do 
      post 'add_feature',
        on: :member,
        action: :add_feature,
        as: 'add_feature'
      post 'remove_feature',
        on: :member,
        action: :remove_feature,
        as: 'remove_feature'
    end
  end
end

app/models/project.rb
class Project
  include MongoMapper::Document

   friendly_id :name

  key :name,                String, required: true
  key :tracker_project_id,  Integer
  key :refreshed_at,        Time

  has_many :bundles
  has_many :features

end

app/controllers/projects/refresh_controller.rb
module Projects
  class RefreshController < ApplicationController
    respond_to :html, :json

    before_filter :project

    def refresh
    end

    def run_refresh
      TrackerIntegration.update_project(@project.tracker_project_id)
      flash[:notice] = 'Features fetched and updated.  Sorry for the wait.'
      redirect_to project_path(@project)
    end

    protected

    def project
      @project = Project.find(params[:project_id])
    end

  end
end

app/controllers/projects/reports_controller.rb
module Projects
  class ReportsController < ApplicationController

    before_filter :project
    before_filter :set_period

    def billing
      features_by_month = Hash.new { |hash, key| hash[key] = Array.new }

      accepted_features.each do |f|
        month = DateTime.new(f.accepted_at.year, f.accepted_at.month)
        features_by_month[month] << f
      end

      @accepted_features_by_month = Hash.new

      features_by_month.keys.each do |key|
        @accepted_features_by_month[key] =
          FeatureSet.new(
            features_by_month[key],
            key.strftime("%b %Y"),
            key
          )
      end

      @accepted_features_by_month
    end

    def billing_detail
      @featureset = FeatureSet.new(accepted_features)
    end

    protected

    def set_period
      now = Time.now
      @period_end =
        begin
          Date.parse(params[:period_end]).to_time
        rescue
          Time.new(now.year, now.month, 31)
        end

      before = (@period_end - 11.months)
      @period_start =
        begin
          Date.parse(params[:period_begin]).to_time
        rescue
          Time.new(before.year, before.month, 1)
        end
    end

    def accepted_features
      @project.features.accepted_in_period(@period_start, @period_end).all
    end

    def project
      @project = Project.find(params[:project_id])
    end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include BilgePump::Controller
    before_filter :tracker_projects_not_in_roadmap, :only => [:index]

  protected
  def tracker_projects_not_in_roadmap 
    tracker_projects = PivotalTracker::Project.all
    roadmap_projects = Project.all

   @projects_not_in_roadmap = tracker_projects.reject do |tp|
      roadmap_projects.any? do |rmp|
        tp.id == rmp.tracker_project_id
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@Project.errors.count, "error")} prohibited this Project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
  
    = f.label :name
    = f.text_field :name, :value => params[:name]
  .field
    = f.label :tracker_project_id
    = f.text_field :tracker_project_id, :value => params[:tracker_project_id]
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing Projects

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', project_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Bundles
    %th Features
    %th Points this month
    %th Last Refreshed
    %th Tracker Project ID
    %th
    %th
  - @projects.each do |project|
    %tr
      %td= link_to project.name, project
      %td= link_to project.bundles.count, project_bundles_path(project)
      %td= link_to project.features.count, project_features_path(project)
      %td= link_to FeatureSet.new(project.features.accepted_in_month(Time.now)).total_cost, project_billing_path(project)
      %td= link_to project.refreshed_at, project_refresh_path(project)
      %td= project.tracker_project_id
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

%h1 Your Tracker Project
%table
  %tr
    %th Name
    %th Tracker Project ID
    %th
  - @projects_not_in_roadmap.each do |tracker_project|
    %tr
      %td= tracker_project.name
      %td= tracker_project.id
      %td= link_to 'add to roadmap', new_project_path(:name => tracker_project.name, :tracker_project_id => tracker_project.id)
%br

= link_to 'New project', new_project_path

app/views/projects/new.html.haml
%h1 New Project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%h2 Project: #{@project.name}

.features
  - set = FeatureSet.new(@project.features)
  %ul
    %li Features in project: #{set.count} #{link_to 'Features', project_features_path(@project)}
    %li Unestimated features: #{set.unestimated_count}
    %li Points this month: #{FeatureSet.new(@project.features.accepted_in_month(Time.now)).total_cost} #{link_to "Billing Report", project_billing_path(@project)}

.actions
  = link_to 'New Bundle', new_project_bundle_path(:project_id => @project.id)
  \|
  = link_to 'Edit', edit_project_path(@project)
  \|
  = link_to "Refresh", project_refresh_path(@project)
  \|
  = link_to 'Projects', projects_path