config/routes.rb
Roadmap::Application.routes.draw do
  root to: 'projects#index'

  resources :projects do 
    get "billing", controller: 'projects/reports', action: :billing
    get "billing_detail", controller: 'projects/reports', action: :billing_detail
    put 'run_refresh', controller: 'projects/refresh', action: :run_refresh
    get 'refresh', controller: 'projects/refresh', action: :refresh
    post 'schedule', controller: 'features', action: :schedule

    resources :features do
      get 'tagged/:value',
        :constraints => { :value =>  /[^\/]+/ },
        on: :collection, 
        action: :tagged,
        as: 'tagged'
    end

    resources :bundles do 
      post 'add_feature',
        on: :member,
        action: :add_feature,
        as: 'add_feature'
      post 'remove_feature',
        on: :member,
        action: :remove_feature,
        as: 'remove_feature'
    end
  end
end

app/models/project.rb
class Project
  include MongoMapper::Document

   friendly_id :name

  key :name,                String, required: true
  key :tracker_project_id,  Integer
  key :refreshed_at,        Time

  has_many :bundles
  has_many :features

end

app/controllers/projects/refresh_controller.rb
module Projects
  class RefreshController < ApplicationController
    respond_to :html, :json

    before_filter :project

    def refresh
    end

    def run_refresh
      TrackerIntegration.update_project(@project.tracker_project_id)
      flash[:notice] = 'Features fetched and updated.  Sorry for the wait.'
      redirect_to project_path(@project)
    end

    protected

    def project
      @project = Project.find(params[:project_id])
    end

  end
end

app/controllers/projects/reports_controller.rb
module Projects
  class ReportsController < ApplicationController

    before_filter :project
    before_filter :set_period

    def billing
      features_by_month = Hash.new { |hash, key| hash[key] = Array.new }

      accepted_features.each do |f|
        month = DateTime.new(f.accepted_at.year, f.accepted_at.month)
        features_by_month[month] << f
      end

      @accepted_features_by_month = Hash.new

      features_by_month.keys.each do |key|
        @accepted_features_by_month[key] =
          FeatureSet.new(
            features_by_month[key],
            key.strftime("%b %Y"),
            key
          )
      end

      @accepted_features_by_month
    end

    def billing_detail
      @featureset = FeatureSet.new(accepted_features)
    end

    protected

    def set_period
      now = Time.now
      @period_end =
        begin
          Date.parse(params[:period_end]).to_time
        rescue
          Time.new(now.year, now.month, 31)
        end

      before = (@period_end - 11.months)
      @period_start =
        begin
          Date.parse(params[:period_begin]).to_time
        rescue
          Time.new(before.year, before.month, 1)
        end
    end

    def accepted_features
      @project.features.accepted_in_period(@period_start, @period_end).all
    end

    def project
      @project = Project.find(params[:project_id])
    end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include BilgePump::Controller
    before_filter :tracker_projects_not_in_roadmap, :only => [:index]

  protected
  def tracker_projects_not_in_roadmap 
    tracker_projects = PivotalTracker::Project.all
    roadmap_projects = Project.all

   @projects_not_in_roadmap = tracker_projects.reject do |tp|
      roadmap_projects.any? do |rmp|
        tp.id == rmp.tracker_project_id
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/reports/billing.html.haml
- sorted_data = @accepted_features_by_month.values.sort
%p Showing #{sorted_data.count} months of #{@project.name.capitalize}

= form_tag project_billing_path, :method => :get do
  %p
    %b Period Beginning:
    = text_field_tag :period_start, url_date(@period_start), class: 'datepicker'

  %p
    %b Period Ending:
    = text_field_tag :period_end, url_date(@period_end), class: 'datepicker'

%p
  View
  = link_to "Billing Detail", project_billing_detail_path(@project, period_begin: params[:period_begin], period_end: params[:period_end])
%table.flipstone-chart{chart_options('data-chart-is_stacked' => 'true')}
  %thead
    %tr
      %th Month
      - sorted_data.each do |month|
        %th= month.label

  %tbody
    %tr
      %th Features
      - sorted_data.each do |month|
        %td= month.total_estimate
    %tr
      %th Bugs
      - sorted_data.each do |month|
        %td= month.bug_types.count * Feature::BugCost
    %tr
      %th Chores
      - sorted_data.each do |month|
        %td= month.chore_types.count * Feature::ChoreCost

%table.billing
  %tr
    %th.month Month
    %th Total Points
    %th Features
    %th Bugs
    %th Chores
  - sorted_data.reverse.each do |month_set|
    %tr
      %td
        - period_month = @accepted_features_by_month.key(month_set)
        - p_begin = period_month.beginning_of_month
        - p_end = period_month.end_of_month
        =link_to month_set.label, project_billing_detail_path(@project, period_begin: url_date(p_begin), period_end: url_date(p_end))

      %td= month_set.total_cost
      %td= month_set.feature_types.count
      %td= month_set.bug_types.count
      %td= month_set.chore_types.count

:javascript
  $(function() {
    $( ".datepicker" ).datepicker({ dateFormat: 'mm-dd-yy' });
  });

app/views/projects/reports/billing_detail.html.haml
.billing-header
  .billing-summary-table
    %table.billing-summary
      %thead
        %tr
          %td Story Type
          %td Count
          %td Points
      %tbody
        %tr
          %td Features
          %td= @featureset.feature_types.count
          %td= @featureset.feature_cost

        %tr
          %td Bugs
          %td= @featureset.bug_types.count
          %td= @featureset.bug_cost

        %tr
          %td Chores
          %td= @featureset.chore_types.count
          %td= @featureset.chore_cost

        %tr.total
          %td TOTAL
          %td= @featureset.features.count
          %td= @featureset.total_cost

  .billing-text
    Showing #{@featureset.total_cost} points accepted for #{@project.name.capitalize} in period.

    %p Period Beginning: #{@period_start.strftime("%b %d %Y")}
    %p Period Ending: #{@period_end.strftime("%b %d %Y")}

%table.billing_detail
  %tr
    %th.date Accepted Date
    %th.longname Feature
    %th Points
    %th Developer
    - @featureset.features_by_accepted_date.reverse.each do |f|
      %tr
        %td= f.accepted_at.strftime("%m/%d/%y")
        %td= f.name
        %td= f.cost
        %td= f.owned_by