config/routes.rb
Roadmap::Application.routes.draw do
  root to: 'projects#index'

  resources :projects do 
    get "billing", controller: 'projects/reports', action: :billing
    get "billing_detail", controller: 'projects/reports', action: :billing_detail
    put 'run_refresh', controller: 'projects/refresh', action: :run_refresh
    get 'refresh', controller: 'projects/refresh', action: :refresh
    post 'schedule', controller: 'features', action: :schedule

    resources :features do
      get 'tagged/:value',
        :constraints => { :value =>  /[^\/]+/ },
        on: :collection, 
        action: :tagged,
        as: 'tagged'
    end

    resources :bundles do 
      post 'add_feature',
        on: :member,
        action: :add_feature,
        as: 'add_feature'
      post 'remove_feature',
        on: :member,
        action: :remove_feature,
        as: 'remove_feature'
    end
  end
end

app/models/bundle.rb
class Bundle
  include MongoMapper::Document

  friendly_id :name
  
 
  
  key :name,          String,    required: true
  key :project_id,    ObjectId

  belongs_to :project

  def estimates_total
    all_features = Feature.where(bundle_ids: self.id).all
    @total=0
    all_features.each do |f| 
        if f.estimate == nil
        elsif f.estimate >= 0
          @total= @total + f.estimate
        end
      end  
    @total
  end

  def unestimated_total 
    all_features = Feature.where(bundle_ids: self.id).all
    @total=0
    all_features.each do |f|
        if f.estimate == nil
        @total= @total + 1
        end
      end  
    @total
  end


end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  include BilgePump::Controller

  model_scope [:project]
  model_class Bundle
  
  def show
    @bundle = find_model(model_scope, params[:id])
    @available_features = Feature.where( :project_id => @bundle.project_id, :bundle_ids => { :$ne => @bundle.id } ).all
    @attached_features = Feature.find_all_by_bundle_ids(@bundle.id)
    respond_with @bundle
  end

  def add_feature
    feature = Feature.find(params[:feature_id])
    bundle = Bundle.find(params[:id])
    feature.bundles.push(bundle)
    feature.save!
    redirect_to project_bundle_path
  end

  def remove_feature
    feature = Feature.find(params[:feature_id])
    bundle = Bundle.find(params[:id])
    feature.bundle_ids.delete(bundle.id)
    feature.save!
    redirect_to project_bundle_path
  end

end

app/views/bundles/_form.html.haml
= form_for [@project, @bundle] do |f|
  -if @bundle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bundle.errors.count, "error")} prohibited this bundle from being saved:"
      %ul
        - @bundle.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    -if params[:project_id]
      = f.text_field :project_id, :type => "hidden", :value => @project.id  
    -else 
      = f.label :project_id
      = f.text_field :project_id
  .actions
    = f.submit 'Save'

app/views/bundles/edit.html.haml
%h1 Editing bundle

= render 'form'

= link_to 'Show', project_bundle_path(@project)
\|
= link_to 'Back', project_bundles_path(@project)

app/views/bundles/index.html.haml
%h1 Listing bundles

%table
  %tr
    %th Name
    %th Total Estimates
    %th Unestimated
    %th Project
    %th
    %th 
  - @bundles.each do |bundle|
    %tr
      %td= bundle.name
      %td= bundle.estimates_total
      %td= bundle.unestimated_total
      %td= bundle.project.name
      %td= link_to 'Show', project_bundle_path(@project,bundle)
      %td= link_to 'Edit', edit_project_bundle_path(@project,bundle)
      %td= link_to 'Destroy', project_bundle_path(@project,bundle), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bundle', new_project_bundle_path(@project)

app/views/bundles/new.html.haml
%h1 New bundle

= render 'form'

= link_to 'Back', project_bundles_path(@project)

app/views/bundles/show.html.haml
%div#notice= notice

%div.bundle-header
  %header 
    #{@bundle.name}
    %span.desc
      #{@bundle.class}
    .action-links 
      = link_to 'Edit', edit_project_bundle_path(@project,@bundle)
      \|
      = link_to 'Back', project_bundles_path(@project)


%div.bundle-details
  - if @attached_features.any? 
    .features-attached
      %header #{@bundle.name.capitalize}
      %ul
        - @attached_features.each do |feature|
          %li.clear
            = feature.name
            = form_tag remove_feature_project_bundle_path(@project,@bundle) do |f|
              = hidden_field_tag :feature_id, feature.id
              = submit_tag '-'
  - if @available_features.any?
    .features-available
      %header Available Features
      %ul
        - @available_features.each do |feature| 
          %li.clear
            = feature.name
            = form_tag add_feature_project_bundle_path(@project,@bundle) do |f|
              = hidden_field_tag :feature_id, feature.id
              = submit_tag '+'