config/routes.rb
Roadmap::Application.routes.draw do
  root to: 'projects#index'

  resources :projects do 
    get "billing", controller: 'projects/reports', action: :billing
    get "billing_detail", controller: 'projects/reports', action: :billing_detail
    put 'run_refresh', controller: 'projects/refresh', action: :run_refresh
    get 'refresh', controller: 'projects/refresh', action: :refresh
    post 'schedule', controller: 'features', action: :schedule

    resources :features do
      get 'tagged/:value',
        :constraints => { :value =>  /[^\/]+/ },
        on: :collection, 
        action: :tagged,
        as: 'tagged'
    end

    resources :bundles do 
      post 'add_feature',
        on: :member,
        action: :add_feature,
        as: 'add_feature'
      post 'remove_feature',
        on: :member,
        action: :remove_feature,
        as: 'remove_feature'
    end
  end
end

app/models/feature.rb
class Feature
  include MongoMapper::Document

  BugCost = 0.25
  ChoreCost = 0.25

  key :accepted_at,           Time
  key :current_state,         String
  key :description,           String
  key :estimate,              Integer
  key :labels,                Array
  key :name,                  String, required: true
  key :owned_by,              String
  key :refreshed_at,          Time
  key :story_id,              Integer
  key :story_type,            String
  key :tracker_project_id,    Integer

  key :project_id,            ObjectId
  belongs_to :project

  key :bundle_ids,            Array
  many :bundles, :in => :bundle_ids

  scope :with_label, -> label do
    where :labels => label
  end

  scope :accepted_in_period, -> period_start, period_end do
    where(:accepted_at.gte => period_start)
      .where(:accepted_at.lte => period_end)
  end

  scope :accepted_in_month, -> time do 
    period_begin = time.beginning_of_month
    t1 = time.end_of_month
    period_end = Time.new(t1.year, t1.month, t1.day, 23, 59, 59)

    accepted_in_period(period_begin, period_end)
  end

  validate :unchanged_after_refreshed

  def unchanged_after_refreshed
    if (changed? && refreshed_at_was.present? && !refreshed_at_changed?)
      errors.add(:base, "Can't update feature attributes after Tracker refresh")
    end
  end

  def cost
    case story_type
      when TrackerIntegration::StoryType::Bug then BugCost
      when TrackerIntegration::StoryType::Chore then ChoreCost
      else ( (estimate && (estimate > 0)) ? estimate : 0 )
    end
  end

  def update(story, refresh_time=Time.now)
    case story.class.to_s
    when 'PivotalTracker::Story'
      fill_from_field_list(
        story,
        TrackerIntegration::Story::StringFields) do |value|
          value
        end

      fill_from_field_list(
        story,
        TrackerIntegration::Story::ArrayFields) do |value|
          value.split ','
        end

      fill_from_field_list(
        story,
        TrackerIntegration::Story::NumericFields) do |value|
          value.to_i
        end

      fill_from_field_list(
        story,
        TrackerIntegration::Story::DateFields) do |value|
          value
        end

      self.refreshed_at = refresh_time
      self.tracker_project_id = story.project_id
      self.story_id = story.id
    else
      super(story)
    end
    self
  end

  protected

  def fill_from_field_list(story, fieldlist)
    fieldlist.each do |field|
      value = story.send field
      if (value)
        self.send "#{field}=", yield(value)
      end
    end
  end

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  include BilgePump::Controller

  model_scope [:project]
  model_class Feature

  def tagged
    @features = Feature.with_label(params[:value]).all
    render 'index' , project_id: @project.id
  end

  def schedule
    @feature = Feature.find(params[:feature_id])

    # create the story in tracker
    story = TrackerIntegration.create_feature_in_tracker(
      params[:tracker_project_id],
      @feature
    )
    
    # set tracker id and save
    @feature.update(story)
    @feature.save

    redirect_to project_feature_path(@project, @feature)
  end

end

app/helpers/feature_helper.rb
module FeatureHelper
  def format_float(number)
    number_with_precision(number, precision:1)
  end
end

app/views/features/_form.html.haml
= form_for [@project, @feature] do |f|
  -if @feature.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feature.errors.count, "error")} prohibited this feature from being saved:"
      %ul
        - @feature.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :estimate
    = f.text_field :estimate
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/features/edit.html.haml
%h1 Editing feature

= render 'form'

= link_to 'Show', project_feature_path(@project,@feature)
\|
= link_to 'Back', project_features_path(@project)

app/views/features/index.html.haml
- set = FeatureSet.new(@features)
- label = params[:value] || ''
%h1 Showing #{@features.count} #{label} features

= flash[:notice]

%table
  %tr
    %th By Estimate
    %th Count
    %th Estimate
    %th Avg
  %tr
    %td Estimated
    %td #{@features.count - set.unestimated_count}
    %td #{set.total_estimate} pts
    %td #{format_float(set.average_estimated_size)} pts
  %tr
    %td Unestimated
    %td #{set.unestimated_count}
    %td -
    %td -

%table
  %tr
    %th By Status
    %th Count
    %th Estimate
    %th Avg
  - [:unscheduled, :unstarted, :started, :accepted].each do |st|
    %tr
      %td= st.capitalize
      %td= set.count_in_state(st)
      %td #{set.total_in_state(st)} pts
      %td -

%table
  %tr
    %th Type
    %th Name
    %th Estimate
    %th Labels
    %th Status
    %th{colspan:3} Actions

  - @features.each do |feature|
    %tr
      %td= feature.story_type
      %td= feature.name
      %td= feature.estimate
      %td
        - feature.labels.each do |tag|
          = link_to tag, tagged_project_features_path(feature.project,value: tag)
      %td= feature.current_state
      - if feature.refreshed_at.present?
        %td{colspan: 3}
          = link_to 'Show', project_feature_path(feature.project,feature)
      - else
        %td= link_to 'Schedule', project_feature_path(feature.project,feature)
        %td= link_to 'Edit', edit_project_feature_path(@project,feature)
        %td= link_to 'Destroy', project_feature_path(@project,feature), :confirm => 'Are you sure?', :method => :delete

%br
= link_to 'New Feature', new_project_feature_path(@project)

app/views/features/new.html.haml
%h1 New feature

= render 'form'

= link_to 'Back', projects_path

app/views/features/show.html.haml
%p#notice= notice

%table
  %tr
    %th Name
    %th Description
    %th Type
    %th Estimate
    %th Labels
    %th Status
    %th Tracker ID
    %th Bundles
    %th Schedule
    %tr
      %td= @feature.name
      %td= @feature.description
      %td= @feature.story_type
      %td= @feature.estimate
      %td
        - @feature.labels.each do |tag|
          = link_to tag, tagged_project_features_path(@project,value: tag)
      %td
        = @feature.current_state
        - if @feature.accepted_at.present?
          (#{@feature.accepted_at.strftime("%m/%d/%y")})
      %td= @feature.story_id
      %td
        - @feature.bundles.each do |b|
          = b.name
      %td  
        - if @feature.story_id == nil
          = form_tag(project_schedule_path(@project), method: :post) do
            %p
              %span 
              = hidden_field_tag 'tracker_project_id', @project.tracker_project_id
            %p
              %span
              = hidden_field_tag 'feature_id', @feature.id
              = submit_tag 'Schedule Feature',
              confirm: 'Are you sure?  This is synchronous for the moment'

= link_to 'Edit', edit_project_feature_path(@project,@feature)
\|
= link_to 'Back', project_features_path